#!/usr/bin/env python

import rospy
from gazebo_msgs.msg import ModelState
from gazebo_msgs.srv import SetModelState
from geometry_msgs.msg import Pose, Twist
import random

def spawn_robot(robot_name, x, y):
    state_msg = ModelState()
    state_msg.model_name = robot_name
    state_msg.pose.position.x = x
    state_msg.pose.position.y = y
    state_msg.pose.position.z = 0.0
    state_msg.pose.orientation.x = 0.0
    state_msg.pose.orientation.y = 0.0
    state_msg.pose.orientation.z = 0.0
    state_msg.pose.orientation.w = 1.0
    state_msg.twist.linear.x = 0.0
    state_msg.twist.linear.y = 0.0
    state_msg.twist.angular.z = 0.0

    rospy.wait_for_service('/gazebo/set_model_state')
    try:
        set_state = rospy.ServiceProxy('/gazebo/set_model_state', SetModelState)
        resp = set_state(state_msg)
    except rospy.ServiceException as e:
        print("Service call failed:", e)

if __name__ == '__main__':
    rospy.init_node('spawn_robots')

    # Names of the robots
    robot_names = ["robot1", "robot2", "robot3", "robot4", "robot5"]

    # Spawn the robots at random positions
    for name in robot_names:
        x = random.uniform(-5, 5)
        y = random.uniform(-5, 5)
        spawn_robot(name, x, y)

    rospy.spin()
